//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.21 at 10:33:56 AM EST 
//


package simple.jaxb.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the simple.jaxb.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonRequest_QNAME = new QName("http://www.myapp.com/Person", "PersonRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: simple.jaxb.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonDto }
     * 
     */
    public PersonDto createPersonDto() {
        return new PersonDto();
    }

    /**
     * Create an instance of {@link AddressDto }
     * 
     */
    public AddressDto createAddressDto() {
        return new AddressDto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.myapp.com/Person", name = "PersonRequest")
    public JAXBElement<PersonDto> createPersonRequest(PersonDto value) {
        return new JAXBElement<PersonDto>(_PersonRequest_QNAME, PersonDto.class, null, value);
    }

}
